"use client";

import { useId, useState, type KeyboardEvent, type ReactNode, type RefObject } from "react";
import { AiHintIcon } from "@/components/ai-hint-icon";
import type { DialogCodeState } from "@/lib/domain/mission";
import type { MissionDictionary } from "@/lib/i18n/dictionaries";
import { repairFieldsByTab, type CodeDiffLine, type DialogPresetId, type DialogRepairField, type RepairTabId } from "@/lib/mission/code-lab";

type CodeLabPanelProps = {
  copy: MissionDictionary["codeLab"]; value: DialogCodeState; presetId: DialogPresetId; repairTabs: readonly RepairTabId[];
  source: string; diff: readonly CodeDiffLine[]; showDiff: boolean; validationErrors: readonly string[]; checking: boolean;
  highlightedFields: readonly DialogRepairField[]; aiHint: string | null; verifiedCount: number; objectiveCount: number; verifiedXp: number;
  onChange: (state: DialogCodeState) => void; onNewSetup: () => void; onRunChecks: () => void; onReset: () => void; onToggleDiff: () => void;
  headingRef: RefObject<HTMLHeadingElement | null>;
};

function AiFieldTip({ visible, hint, label }: { visible: boolean; hint: string | null; label: string }) {
  if (!visible || !hint) return null;
  return <button className="ai-field-tip" type="button" data-tooltip={hint} aria-label={`${label}: ${hint}`}><AiHintIcon className="ai-hint-icon" /></button>;
}

export function CodeLabPanel({ copy, value, presetId, repairTabs, source, diff, showDiff, validationErrors, checking, highlightedFields, aiHint, verifiedCount, objectiveCount, verifiedXp, onChange, onNewSetup, onRunChecks, onReset, onToggleDiff, headingRef }: CodeLabPanelProps) {
  const [activeTab, setActiveTab] = useState<RepairTabId>(repairTabs[0] ?? "accessibility");
  const tabId = useId();
  const isHighlighted = (field: DialogRepairField): boolean => highlightedFields.some((candidate) => candidate === field);
  const tipFor = (field: DialogRepairField) => <AiFieldTip visible={isHighlighted(field)} hint={aiHint} label={copy.aiTooltipLabel} />;
  const tabLabel = (id: RepairTabId): string => copy.tabs[id];
  const moveTabFocus = (event: KeyboardEvent<HTMLButtonElement>, id: RepairTabId) => {
    if (event.key !== "ArrowLeft" && event.key !== "ArrowRight" && event.key !== "Home" && event.key !== "End") return;
    event.preventDefault();
    const current = repairTabs.findIndex((candidate) => candidate === id);
    const index = event.key === "Home" ? 0 : event.key === "End" ? repairTabs.length - 1 : event.key === "ArrowRight" ? (current + 1) % repairTabs.length : (current - 1 + repairTabs.length) % repairTabs.length;
    const next = repairTabs[index] ?? repairTabs[0];
    if (!next) return;
    setActiveTab(next);
    event.currentTarget.ownerDocument.getElementById(`${tabId}-${next}-tab`)?.focus();
  };
  const control = (field: DialogRepairField, label: string, child: ReactNode) => <div className={`repair-control ${isHighlighted(field) ? "ai-highlight" : ""}`}><label htmlFor={`repair-${field}`}>{label}</label>{tipFor(field)}{child}</div>;
  const toggle = (field: "ariaModal" | "escapeCloses" | "focusContainment" | "focusRestoration" | "reducedMotionSafe", label: string) => <div className={`repair-control repair-toggle ${isHighlighted(field) ? "ai-highlight" : ""}`}><label className="toggle-control"><input id={`repair-${field}`} type="checkbox" checked={value[field]} onChange={(event) => onChange({ ...value, [field]: event.target.checked })} /><span>{label}</span></label>{tipFor(field)}</div>;

  const panels: Record<RepairTabId, ReactNode> = {
    accessibility: <>{control("dialogRole", copy.fields.dialogRole, <select id="repair-dialogRole" value={value.dialogRole} onChange={(event) => onChange({ ...value, dialogRole: event.target.value === "dialog" ? "dialog" : "none" })}><option value="none">{copy.values.none}</option><option value="dialog">dialog</option></select>)}{control("ariaLabelledBy", copy.fields.labelledBy, <select id="repair-ariaLabelledBy" value={value.ariaLabelledBy} onChange={(event) => onChange({ ...value, ariaLabelledBy: event.target.value === "dialog-title" ? "dialog-title" : "none" })}><option value="none">{copy.values.none}</option><option value="dialog-title">dialog-title</option></select>)}{control("ariaDescribedBy", copy.fields.describedBy, <select id="repair-ariaDescribedBy" value={value.ariaDescribedBy} onChange={(event) => onChange({ ...value, ariaDescribedBy: event.target.value === "dialog-description" ? "dialog-description" : "none" })}><option value="none">{copy.values.none}</option><option value="dialog-description">dialog-description</option></select>)}{toggle("ariaModal", copy.fields.ariaModal)}{toggle("escapeCloses", copy.fields.escapeCloses)}{toggle("focusContainment", copy.fields.focusContainment)}{toggle("focusRestoration", copy.fields.focusRestoration)}</>,
    css: <>{control("actionDisplay", copy.fields.actionDisplay, <select id="repair-actionDisplay" value={value.actionDisplay} onChange={(event) => onChange({ ...value, actionDisplay: event.target.value === "flex" ? "flex" : "grid" })}><option>grid</option><option>flex</option></select>)}{control("actionDirection", copy.fields.actionDirection, <select id="repair-actionDirection" value={value.actionDirection} onChange={(event) => onChange({ ...value, actionDirection: event.target.value === "row" ? "row" : "column" })}><option>column</option><option>row</option></select>)}{control("actionAlign", copy.fields.actionAlign, <select id="repair-actionAlign" value={value.actionAlign} onChange={(event) => onChange({ ...value, actionAlign: event.target.value === "center" ? "center" : "stretch" })}><option>stretch</option><option>center</option></select>)}{control("actionJustify", copy.fields.actionJustify, <select id="repair-actionJustify" value={value.actionJustify} onChange={(event) => onChange({ ...value, actionJustify: event.target.value === "flex-end" ? "flex-end" : event.target.value === "space-between" ? "space-between" : "flex-start" })}><option>flex-start</option><option>flex-end</option><option>space-between</option></select>)}{control("actionGap", copy.fields.actionGap, <select id="repair-actionGap" value={value.actionGap} onChange={(event) => onChange({ ...value, actionGap: event.target.value === "16" ? 16 : event.target.value === "8" ? 8 : 0 })}><option value={0}>0px</option><option value={8}>8px</option><option value={16}>16px</option></select>)}</>,
    motion: <>{control("motionDuration", copy.fields.motionDuration, <select id="repair-motionDuration" value={value.motionDuration} onChange={(event) => onChange({ ...value, motionDuration: event.target.value === "1200" ? 1200 : 8000 })}><option value={8000}>8s</option><option value={1200}>1.2s</option></select>)}{control("motionDistance", copy.fields.motionDistance, <select id="repair-motionDistance" value={value.motionDistance} onChange={(event) => onChange({ ...value, motionDistance: event.target.value === "12" ? 12 : 48 })}><option value={48}>48px</option><option value={12}>12px</option></select>)}{toggle("reducedMotionSafe", copy.fields.reducedMotionSafe)}</>,
    stream: <>{control("streamProtocol", copy.fields.streamProtocol, <select id="repair-streamProtocol" value={value.streamProtocol} onChange={(event) => onChange({ ...value, streamProtocol: event.target.value === "event-stream" ? "event-stream" : "buffered" })}><option value="buffered">buffered</option><option value="event-stream">event-stream</option></select>)}{control("streamParsing", copy.fields.streamParsing, <select id="repair-streamParsing" value={value.streamParsing} onChange={(event) => onChange({ ...value, streamParsing: event.target.value === "event-lines" ? "event-lines" : "raw" })}><option value="raw">raw text</option><option value="event-lines">event lines</option></select>)}{control("streamReconnect", copy.fields.streamReconnect, <select id="repair-streamReconnect" value={value.streamReconnect} onChange={(event) => onChange({ ...value, streamReconnect: event.target.value === "bounded" ? "bounded" : "unbounded" })}><option value="unbounded">unbounded</option><option value="bounded">bounded</option></select>)}</>,
    state: <>{control("stateUpdate", copy.fields.stateUpdate, <select id="repair-stateUpdate" value={value.stateUpdate} onChange={(event) => onChange({ ...value, stateUpdate: event.target.value === "immutable" ? "immutable" : "mutate" })}><option value="mutate">mutate</option><option value="immutable">immutable</option></select>)}{control("stateReset", copy.fields.stateReset, <select id="repair-stateReset" value={value.stateReset} onChange={(event) => onChange({ ...value, stateReset: event.target.value === "reset" ? "reset" : "keep-stale" })}><option value="keep-stale">keep stale</option><option value="reset">reset</option></select>)}{control("stateSource", copy.fields.stateSource, <select id="repair-stateSource" value={value.stateSource} onChange={(event) => onChange({ ...value, stateSource: event.target.value === "single" ? "single" : "duplicated" })}><option value="duplicated">duplicated</option><option value="single">single source</option></select>)}</>,
  };

  return <section className="panel code-lab" aria-labelledby="code-lab-heading">
    <div className="section-heading-row"><div><p className="eyebrow">{copy.eyebrow}</p><h2 id="code-lab-heading" ref={headingRef} tabIndex={-1}>{copy.heading}</h2><p>{copy.description}</p></div><span className="safe-badge">{copy.safeBadge}</span></div>
    <div className="repair-context-bar"><div><span>{copy.presetLabel}</span><strong>{copy.presetName[presetId]}</strong><p>{copy.presetBehavior[presetId]}</p></div><button className="secondary-action" type="button" onClick={onNewSetup}>{copy.actions.newSetup}</button><p className="sr-only" aria-live="polite" aria-atomic="true">{copy.presetName[presetId]}. {copy.presetBehavior[presetId]}</p></div>
    <div className="verified-xp-console" aria-label={copy.verifiedProgressLabel(verifiedCount, verifiedXp)}><div><span>{copy.verifiedXp}</span><strong data-testid="verified-xp">{verifiedXp} / 300 XP</strong></div><ol aria-hidden="true">{Array.from({ length: objectiveCount }, (_, index) => <li className={index < verifiedCount ? "is-verified" : ""} key={index}>✓</li>)}</ol><small>{copy.verifiedProgressHelp}</small></div>
    <div className="repair-tabs" role="tablist" aria-label={copy.tabs.label}>{repairTabs.map((id) => { const count = repairFieldsByTab[id].filter(isHighlighted).length; return <button key={id} id={`${tabId}-${id}-tab`} className={count > 0 ? "ai-tab-highlight" : ""} type="button" role="tab" tabIndex={activeTab === id ? 0 : -1} aria-selected={activeTab === id} aria-controls={`${tabId}-${id}-panel`} onClick={() => setActiveTab(id)} onKeyDown={(event) => moveTabFocus(event, id)}>{tabLabel(id)}{count > 0 && <span className="tab-hint-count" aria-label={copy.tabs.hintCount(count)}>{count}</span>}</button>; })}</div>
    {repairTabs.map((id) => <fieldset key={id} id={`${tabId}-${id}-panel`} className="code-controls" role="tabpanel" aria-labelledby={`${tabId}-${id}-tab`} hidden={activeTab !== id}><legend>{tabLabel(id)}</legend>{panels[id]}</fieldset>)}
    {validationErrors.length > 0 && <div className="validation-errors" role="alert"><strong>{copy.validationHeading}</strong><ul>{validationErrors.map((error) => <li key={error}>{error}</li>)}</ul></div>}
    <div className="direct-actions"><button className="primary-action check-attack" type="button" onClick={onRunChecks} disabled={checking}>{checking ? copy.actions.checking : copy.actions.check}</button><button className="text-action" type="button" onClick={onReset}>{copy.actions.reset}</button></div>
    <details className="technical-details" open={showDiff} onToggle={(event) => { if (event.currentTarget.open !== showDiff) onToggleDiff(); }}><summary>{copy.actions.diff}</summary><div className="code-view" aria-label={copy.diffLabel}>{showDiff ? <pre>{diff.map((line, index) => <code className={`diff-${line.kind}`} key={`${line.kind}-${index}`}>{line.kind === "added" ? "+ " : line.kind === "removed" ? "- " : "  "}{line.text}{"\n"}</code>)}</pre> : <pre><code>{source}</code></pre>}</div></details>
    <div className="code-view current-source" aria-label={copy.sourceLabel}><pre><code>{source}</code></pre></div>
  </section>;
}
